version: '3.8'

services:
  # MySQL Database Service
  db:
    env_file:
      - ./.env
    image: mysql:8.0 # Using MySQL 8.0 image
    container_name: japaneseriddle_db
    volumes:
      # Persistent volume for database data, so data is not lost on container restart
      - db_data:/var/lib/mysql
    ports:
      # Expose port 3307 for direct access from host (optional, mainly for debugging)
      - "3308:3306"
    networks:
      # Connect to the custom application network
      - app_network
    healthcheck: # Added healthcheck for the database service
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pyour_root_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 80s # Give MySQL time to start before checking

  # Flask Application Service (served by Gunicorn)
  web:
    env_file:
      - ./.env
    build:
      context: . # Build context is the current directory
      dockerfile: Dockerfile.web # Use the Dockerfile.web to build this service's image
    container_name: flask_japanese_riddle_app
    restart: always # Always restart the container if it stops
    ports:
      # Expose port 8012 for internal communication with Nginx (optional for external access)
      - "8012:8012"
    depends_on:
      # Ensure the database service is up and healthy before starting the web service
      db:
        condition: service_healthy # Changed condition to wait for healthcheck
    networks:
      # Connect to the custom application network
      - app_network

volumes:
  # Define named volume for database persistence
  db_data:

networks:
  # Define a custom bridge network for inter-service communication
  app_network:
    driver: bridge
