server {
    listen 80;
    server_name example.com;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name example.com;

    # Replace these with your actual SSL certificate and key paths
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    # Serve the pre-generated song HTML from the cache directly
    location ~ ^/lyrics/cache/(.*)$ {
        # The corrected alias path
        alias /media/system/web/webapp/flask-lyrics/app/static/cache/$1;
        expires max;
        add_header Cache-Control "public";
    }

    # Catch-all location to proxy requests to the Flask web app
    location / {
        if ($host != "example.com") {
            return 502;
        }
        # Assuming Flask is running on localhost from Nginx's perspective
        proxy_pass http://localhost:8012;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header Charset;
    }
}
